paperbadger:
  build: .
  ports:
    - 5000:5000
  links:
    - mongo:mongo
  env_file:
    - env.docker
  environment:
    - MONGOLAB_URI=mongodb://mongo:27017/test

mongo:
  image: mongo:2
  # volumes:    # to persist database between runs
  #   - /data/db
